# Generated by Django 5.0.3 on 2024-04-19 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameofchanel', models.CharField(max_length=30)),
                ('films', models.IntegerField()),
                ('views', models.IntegerField()),
            ],
        ),
    ]
