# Generated by Django 5.0.3 on 2024-04-19 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='auditory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameofchanel', models.CharField(max_length=30)),
                ('subscribers', models.IntegerField()),
                ('likes', models.IntegerField()),
            ],
        ),
    ]
